cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

cask "jdownloader2"
cask "vlc"
cask "transmission"
cask "prusaslicer"
cask "steam"
cask "arduino-ide"
